[project]
name = "rag-system"
version = "0.1.0"
description = "RAG SYSTEM"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.108",
    "botocore[crt]>=1.43.108",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.6",
    "pypdf>=6.19.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
